[package]
authors = ["Antonio Garcés", "agarces@senatorhr.es"]
edition = "2021"
name = "winget_basico"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
